# Configuration for graphrag-anthropic-llamaindex

anthropic:
  api_key: "YOUR_ANTHROPIC_API_KEY"
  model: "claude-3-opus-20240620"
  # api_base_url: "https://api.anthropic.com"

embedding_model:
  name: "intfloat/multilingual-e5-small"

chunking:
  chunk_size: 1024
  chunk_overlap: 20

input_dir: "./data"
output_dir: "./graphrag_output"

vector_store:
  type: "lancedb" # or "default"
  lancedb:
    uri: "./graphrag_output/lancedb_main"
    table_name: "vectors"

community_vector_store:
  type: "lancedb" # or "default"
  lancedb:
    uri: "./graphrag_output/lancedb_communities"
    table_name: "community_vectors"

entity_vector_store:
  type: "lancedb" # or "default"
  lancedb:
    uri: "./graphrag_output/lancedb_entities"
    table_name: "entities_vectors"

community_detection:
  max_cluster_size: 10
  use_lcc: True
  seed: 42