# Configuration for graphrag-anthropic-llamaindex with AWS Bedrock

# LLMプロバイダー選択: AWS Bedrock
llm_provider: "bedrock"

# AWS Bedrock設定
bedrock:
  model: "anthropic.claude-3-sonnet-20240229-v1:0"
  region: "us-east-1"
  # AWS認証情報は環境変数から取得
  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN

embedding_model:
  name: "intfloat/multilingual-e5-small"

chunking:
  chunk_size: 1024
  chunk_overlap: 20

input_dir: "./data"
output_dir: "./graphrag_output_bedrock"

# Ignore patterns for file processing
ignore_patterns:
  - "*.tmp"
  - "*.log"
  - "*.cache"
  - "*.bak"
  - "*.swp"
  - "*.DS_Store"
  - "Thumbs.db"
  - ".git/*"
  - ".gitignore"
  - "__pycache__/*"
  - "*.pyc"
  - "node_modules/*"
  - ".env"
  - ".env.*"

vector_store:
  type: "lancedb"
  lancedb:
    uri: "lancedb_main"
    table_name: "vectors"

community_vector_store:
  type: "lancedb"
  lancedb:
    uri: "lancedb_communities"
    table_name: "community_vectors"

entity_vector_store:
  type: "lancedb"
  lancedb:
    uri: "lancedb_entities"
    table_name: "entities_vectors"

community_detection:
  max_cluster_size: 10
  use_lcc: True
  seed: 42